version: '3'

services:
    chromium:
        image: lscr.io/linuxserver/chromium:latest
        container_name: chromium
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - CUSTOM_USER=${USERNAME}
            - PASSWORD=${PASSWORD}
        ports:
            - ${PORT}:3000
            - ${SSL_PORT}:3001
        volumes:
            - ./data:/config:z
        shm_size: 1gb
        restart: unless-stopped
